# Generated by Django 2.0.5 on 2018-05-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatShiroShop', '0002_auto_20180508_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
