# Generated by Django 2.0.5 on 2018-05-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatShiroShop', '0003_song_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
