# Generated by Django 2.0.5 on 2018-05-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatShiroShop', '0004_auto_20180508_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
