# Generated by Django 2.0.5 on 2018-05-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatShiroShop', '0007_auto_20180514_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Song Name'),
        ),
        migrations.AlterField(
            model_name='song',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
    ]
