# Generated by Django 2.0.5 on 2018-05-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatShiroShop', '0008_auto_20180514_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
