# Generated by Django 2.0.5 on 2018-05-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatShiroShop', '0010_auto_20180515_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='signature',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
