# Generated by Django 2.0.5 on 2018-05-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatShiroShop', '0012_song_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
