# Generated by Django 2.0.5 on 2018-05-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatShiroShop', '0013_auto_20180517_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='songs',
            field=models.ManyToManyField(blank=True, to='DatShiroShop.Song'),
        ),
    ]
